[package]
name = "froglin_gateway"
authors = [ "zerok-labs" ]
compiler_version = ">=0.30.0"
type = "contract"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.46.7", directory="noir-projects/aztec-nr/aztec" }
value_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.46.7", directory="noir-projects/aztec-nr/value-note"}

zkl_utils = { path = "../../libs/utils" }
