services:
  ethereum:
    image: aztecprotocol/foundry:25f24e677a6a32a62512ad4f561995589ac2c7dc-${ARCH_TAG:-amd64}
    entrypoint: >
      sh -c '
      if [ -n "$$FORK_BLOCK_NUMBER" ] && [ -n "$$FORK_URL" ]; then
        exec anvil --silent -p "$$ANVIL_PORT" --host 0.0.0.0 --chain-id 31337 --fork-url "$$FORK_URL" --fork-block-number "$$FORK_BLOCK_NUMBER"
      else
        exec anvil --silent -p "$$ANVIL_PORT" --host 0.0.0.0 --chain-id 31337
      fi'
    ports:
      - "${ANVIL_PORT:-8545}:${ANVIL_PORT:-8545}"
    environment:
      FORK_URL:
      FORK_BLOCK_NUMBER:
      ANVIL_PORT: ${ANVIL_PORT:-8545}

  aztec:
    image: "aztecprotocol/aztec"
    ports:
      - "${PXE_PORT:-8080}:${PXE_PORT:-8080}"
    environment:
      DEBUG: "aztec:simulator:client_execution_context, aztec:sandbox, aztec:avm_simulator:debug_log"
      HOST_WORKDIR: "${PWD}" # Loaded from the user shell to show log files absolute path in host
      ETHEREUM_HOST: ${ETHEREUM_HOST:-http://ethereum:${ANVIL_PORT:-8545}}
      L1_CHAIN_ID: 31337
      ARCHIVER_POLLING_INTERVAL_MS: 500
      ARCHIVER_VIEM_POLLING_INTERVAL_MS: 500
      PXE_BLOCK_POLLING_INTERVAL_MS: 600
      SEQ_TX_POLLING_INTERVAL_MS: 400
      P2P_BLOCK_CHECK_INTERVAL_MS: 700
      WS_BLOCK_CHECK_INTERVAL_MS: 1000
      PXE_PORT: ${PXE_PORT:-8080}
      PORT: ${AZTEC_NODE_PORT:-8080}
      TEST_ACCOUNTS: ${TEST_ACCOUNTS:-false}
    depends_on:
      - ethereum
    command: "start --sandbox"
