
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  L1EventPayload,
  loadContractArtifact,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type UnencryptedL2Log,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import FroglinGatewayContractArtifactJson from '../target/froglin_gateway-FroglinGateway.json' assert { type: 'json' };
export const FroglinGatewayContractArtifact = loadContractArtifact(FroglinGatewayContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract FroglinGateway;
 */
export class FroglinGatewayContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, FroglinGatewayContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, FroglinGatewayContract.artifact, wallet) as Promise<FroglinGatewayContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<FroglinGatewayContract>(PublicKeys.default(), wallet, FroglinGatewayContractArtifact, FroglinGatewayContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<FroglinGatewayContract>(publicKeys, wallet, FroglinGatewayContractArtifact, FroglinGatewayContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof FroglinGatewayContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<FroglinGatewayContract['methods'][M]>
  ) {
    return new DeployMethod<FroglinGatewayContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      FroglinGatewayContractArtifact,
      FroglinGatewayContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return FroglinGatewayContractArtifact;
  }
  

  public static get storage(): ContractStorageLayout<'game_master' | 'accounts_count' | 'accounts' | 'froglin_count' | 'stashes' | 'epoch_count' | 'epoch_duration' | 'epoch_start_time' | 'leaderboard' | 'public_stash' | 'swap_proposal_count' | 'swap_proposals' | 'battle_proposals' | 'battle_proposal_count' | 'battle_notes_1' | 'battle_notes_2' | 'battle_winners' | 'date_proposals' | 'date_proposal_count' | 'date_notes_1' | 'date_notes_2' | 'player_events'> {
      return {
        game_master: {
      slot: new Fr(1n),
    },
accounts_count: {
      slot: new Fr(3n),
    },
accounts: {
      slot: new Fr(4n),
    },
froglin_count: {
      slot: new Fr(5n),
    },
stashes: {
      slot: new Fr(6n),
    },
epoch_count: {
      slot: new Fr(7n),
    },
epoch_duration: {
      slot: new Fr(8n),
    },
epoch_start_time: {
      slot: new Fr(9n),
    },
leaderboard: {
      slot: new Fr(10n),
    },
public_stash: {
      slot: new Fr(11n),
    },
swap_proposal_count: {
      slot: new Fr(12n),
    },
swap_proposals: {
      slot: new Fr(13n),
    },
battle_proposals: {
      slot: new Fr(14n),
    },
battle_proposal_count: {
      slot: new Fr(15n),
    },
battle_notes_1: {
      slot: new Fr(16n),
    },
battle_notes_2: {
      slot: new Fr(17n),
    },
battle_winners: {
      slot: new Fr(18n),
    },
date_proposals: {
      slot: new Fr(19n),
    },
date_proposal_count: {
      slot: new Fr(20n),
    },
date_notes_1: {
      slot: new Fr(21n),
    },
date_notes_2: {
      slot: new Fr(22n),
    },
player_events: {
      slot: new Fr(23n),
    }
      } as ContractStorageLayout<'game_master' | 'accounts_count' | 'accounts' | 'froglin_count' | 'stashes' | 'epoch_count' | 'epoch_duration' | 'epoch_start_time' | 'leaderboard' | 'public_stash' | 'swap_proposal_count' | 'swap_proposals' | 'battle_proposals' | 'battle_proposal_count' | 'battle_notes_1' | 'battle_notes_2' | 'battle_winners' | 'date_proposals' | 'date_proposal_count' | 'date_notes_1' | 'date_notes_2' | 'player_events'>;
    }
    

  public static get notes(): ContractNotes<'WinNote' | 'ValueNote' | 'StashNote' | 'BattleNote' | 'EventsNote' | 'DateNote' | 'PlayerNote'> {
    return {
      WinNote: {
          id: new NoteSelector(6),
        },
ValueNote: {
          id: new NoteSelector(0),
        },
StashNote: {
          id: new NoteSelector(5),
        },
BattleNote: {
          id: new NoteSelector(1),
        },
EventsNote: {
          id: new NoteSelector(3),
        },
DateNote: {
          id: new NoteSelector(2),
        },
PlayerNote: {
          id: new NoteSelector(4),
        }
    } as ContractNotes<'WinNote' | 'ValueNote' | 'StashNote' | 'BattleNote' | 'EventsNote' | 'DateNote' | 'PlayerNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** accept_battle_proposal(proposal_id: integer, choices: integer) */
    accept_battle_proposal: ((proposal_id: (bigint | number), choices: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** accept_date_proposal(proposal_id: integer, dating_froglin_type: integer, choices: integer) */
    accept_date_proposal: ((proposal_id: (bigint | number), dating_froglin_type: (bigint | number), choices: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** accept_swap_proposal(proposal_id: integer) */
    accept_swap_proposal: ((proposal_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** advance_epoch() */
    advance_epoch: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** cancel_battle_proposal(proposal_id: integer) */
    cancel_battle_proposal: ((proposal_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** cancel_date_proposal(proposal_id: integer) */
    cancel_date_proposal: ((proposal_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** cancel_swap_proposal(proposal_id: integer) */
    cancel_swap_proposal: ((proposal_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** capture_froglin(froglin_type: integer) */
    capture_froglin: ((froglin_type: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** check_registration(player: struct) */
    check_registration: ((player: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_swap_proposal(proposal_id: integer) */
    claim_swap_proposal: ((proposal_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_winnings(froglin_type: integer) */
    claim_winnings: ((froglin_type: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** compare_battle_choices(choice1: integer, choice2: integer) */
    compare_battle_choices: ((choice1: (bigint | number), choice2: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** compare_date_choices(choice1: integer, choice2: integer) */
    compare_date_choices: ((choice1: (bigint | number), choice2: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, packed_note_content: array) */
    compute_note_hash_and_optionally_a_nullifier: ((contract_address: AztecAddressLike, nonce: FieldLike, storage_slot: FieldLike, note_type_id: FieldLike, compute_nullifier: boolean, packed_note_content: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** construct_public() */
    construct_public: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_battle_proposal(offered_froglin_type: integer, wanted_froglin_type: integer, choices: integer) */
    create_battle_proposal: ((offered_froglin_type: (bigint | number), wanted_froglin_type: (bigint | number), choices: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_date_proposal(dating_froglin_type: integer, choices: integer) */
    create_date_proposal: ((dating_froglin_type: (bigint | number), choices: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_random_froglin(choice1: integer, choice2: integer) */
    create_random_froglin: ((choice1: (bigint | number), choice2: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_swap_proposal(offered_froglin_type: integer, wanted_froglin_type: integer) */
    create_swap_proposal: ((offered_froglin_type: (bigint | number), wanted_froglin_type: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** join_event(event_name: field) */
    join_event: ((event_name: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** leave_event(event_name: field) */
    leave_event: ((event_name: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** make_battle(proposal_id: integer) */
    make_battle: ((proposal_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** make_date(proposal_id: integer) */
    make_date: ((proposal_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_log(log_plaintext: struct, tx_hash: field, unique_note_hashes_in_tx: struct, first_nullifier_in_tx: field, recipient: struct) */
    process_log: ((log_plaintext: { storage: FieldLike[], len: (bigint | number) }, tx_hash: FieldLike, unique_note_hashes_in_tx: { storage: FieldLike[], len: (bigint | number) }, first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** recover_froglin(froglin_type: integer) */
    recover_froglin: ((froglin_type: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register(name: field) */
    register: ((name: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** registered(player: struct) */
    registered: ((player: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** start_event(froglin_count: integer, epoch_count: integer, epoch_duration: integer, epoch_start_time: integer) */
    start_event: ((froglin_count: (bigint | number), epoch_count: (bigint | number), epoch_duration: (bigint | number), epoch_start_time: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_notes() */
    sync_notes: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_name(name: field) */
    update_name: ((name: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_accounts_count() */
    view_accounts_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_active_battle_proposals() */
    view_active_battle_proposals: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_active_date_proposals() */
    view_active_date_proposals: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_active_swap_proposals() */
    view_active_swap_proposals: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_battle_proposal(proposal_id: integer) */
    view_battle_proposal: ((proposal_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_battle_proposals_count() */
    view_battle_proposals_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_claimable_swaps(trader_id: integer) */
    view_claimable_swaps: ((trader_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_date_proposal(proposal_id: integer) */
    view_date_proposal: ((proposal_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_date_proposals_count() */
    view_date_proposals_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_epoch_count() */
    view_epoch_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_epoch_duration() */
    view_epoch_duration: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_epoch_start_time() */
    view_epoch_start_time: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_events(player: struct) */
    view_events: ((player: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_events_note(player: struct) */
    view_events_note: ((player: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_froglin_count() */
    view_froglin_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_leaderboard() */
    view_leaderboard: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_name(player: struct) */
    view_name: ((player: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_profile(player: struct) */
    view_profile: ((player: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_stash(player: struct) */
    view_stash: ((player: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_swap_proposal(proposal_id: integer) */
    view_swap_proposal: ((proposal_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_won_in_battle(player: struct) */
    view_won_in_battle: ((player: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
